version: '3.4'
services:
  db:
    image: oliverrah/mysql-recipe-drink-finder
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: hbstudent
      MYSQL_PASSWORD: hbstudent
      MYSQL_DATABASE: drink_database
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  recipe-drink-finder:
    image: oliverrah/recipe-drink-finder
    restart: always
    build: ./recipe-drink-finder
    working_dir: /recipe-drink-finder
    environment:
        TZ: America/Sao_Paulo
        SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./recipe-drink-finder:/recipe-drink-finder
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
networks:
    udemy-network:
        driver: bridge